import { AccountWithInstitution, AvailableWithByBank, BeneficiaryCustomer, BeneficiaryInstitution, Description, Discrepancies, InstructingParty, IntermediaryInstitution, NonBankIssuer, OrderingCustomer, OrderingInstitution, ReceiverCorrespondent, ReceiverInstitution, RegulatoryReporting, RelatedReference, RemittanceInformation, SasHeader, SenderCorrespondent, SenderInstitution, SenderReference, SenderToReceiverInformation, SendingInstitution, Tbml, ThirdReimbursementInstitution, UdfFields } from './common.entity';
export declare class CommonScreeningRequest {
    id: number;
    sasHeader: SasHeader;
    senderInstitution: SenderInstitution;
    receiverInstitution: ReceiverInstitution;
    senderReference: SenderReference;
    relatedReference: RelatedReference;
    instructingParty: InstructingParty;
    valueDate: string;
    transferCurrency: string;
    transferAmount: string;
    udfFields: UdfFields;
    orderingCustomer: OrderingCustomer;
    nonBankIssuer: NonBankIssuer;
    availableWithByBank: AvailableWithByBank;
    sendingInstitution: SendingInstitution;
    orderingInstitution: OrderingInstitution;
    senderCorrespondent: SenderCorrespondent;
    receiverCorrespondent: ReceiverCorrespondent;
    thirdReimbursementInstitution: ThirdReimbursementInstitution;
    intermediaryInstitution: IntermediaryInstitution;
    accountWithInstitution: AccountWithInstitution;
    beneficiaryInstitution: BeneficiaryInstitution;
    beneficiaryCustomer: BeneficiaryCustomer;
    remittanceInformation: RemittanceInformation;
    senderToReceiverInformation: SenderToReceiverInformation;
    regulatoryReporting: RegulatoryReporting;
    discrepancies: Discrepancies;
    description: Description;
    tbml: Tbml;
    payload: string;
}
